#!/bin/bash
##SBATCH --mail-user=songlin3@msu.edu
##SBATCH --mail-type=FAIL
#SBATCH -J gMMM_XXX
#SBATCH -e test.err
#SBATCH -o test.out
#SBATCH -N 1 -c 1 --gres=gpu:1
#SBATCH --mem=4G
#SBATCH --time=3:30:00

echo $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

#-------------- Load Modules ------------------
module load GNU/6.4.0-2.28  OpenMPI/2.1.2-CUDA
module load Amber/18

exe=$AMBERHOME/bin/pmemd.cuda                  

#-------------- Run job -----------------------
echo 'RUN AMBER JOB'
# running command
$exe -O -i XXX_min.in -o XXX_min.out -c glx-ni_step0.inpcrd -p glx-ni_step0.prmtop -r XXX_min.rst -x XXX_min.netcdf -inf XXX_min.mdinfo -ref glx-ni_step0.inpcrd
$exe -O -i XXX_heat.in -o XXX_heat.out -c XXX_min.rst -p glx-ni_step0.prmtop -r XXX_heat.rst -x XXX_heat.netcdf -inf XXX_heat.mdinfo -ref XXX_min.rst
$exe -O -i XXX_eq.in -o XXX_eq.out -c XXX_heat.rst -p glx-ni_step0.prmtop -r XXX_eq.rst -x XXX_eq.netcdf -inf XXX_eq.mdinfo -ref XXX_heat.rst
$exe -O -i XXX_us.in -o XXX_us.out -c XXX_eq.rst -p glx-ni_step0.prmtop -r XXX_us.rst -x XXX_us.netcdf -inf XXX_us.mdinfo -ref XXX_eq.rst
if grep "Total wall time" XXX_us.out;then
   echo "done"
else
   sbatch XXX.pbs
fi
