#!/bin/bash
##SBATCH --mail-user=songlin3@msu.edu
##SBATCH --mail-type=FAIL
#SBATCH -J eMMM_XXX
#SBATCH -e test.err
#SBATCH -o test.out
#SBATCH -N 1 -c 1 --gres=gpu:1
#SBATCH --mem=4G
#SBATCH --time=6:00:00

echo $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

#-------------- Load Modules ------------------
module purge
ulimit -c 0
ml -* GCC/7.3.0-2.30 OpenMPI/3.1.1-CUDA Amber/18-AmberTools-19

exe=$AMBERHOME/bin/pmemd.cuda                  

#-------------- Run job -----------------------
echo 'RUN AMBER JOB'
# running command
$exe -O -i XXX_eq.in -o XXX_eq.out -c PPP_eq.rst -p glx-co_1264_final.prmtop -r XXX_eq.rst -x XXX_eq.netcdf -inf XXX_eq.mdinfo -ref PPP_eq.rst
if grep "Total wall time" XXX_eq.out;then
   echo "done"
   sbatch XXX_us.pbs
   cp XXX_eq.rst ../NNN/
   cd ../NNN/
   sbatch NNN_eq.pbs
else
   sbatch XXX_eq.pbs
fi
