#!/bin/bash
##SBATCH --mail-user=songlin3@msu.edu
##SBATCH --mail-type=FAIL
#SBATCH -J s1_50
#SBATCH -e test.err
#SBATCH -o test.out
#SBATCH -N 1 -c 1 --gres=gpu:1
#SBATCH --mem=8G
#SBATCH --time=00:30:00

echo $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

#-------------- Load Modules ------------------
module load GNU/6.4.0-2.28  OpenMPI/2.1.2-CUDA
module load Amber/18

exe=$AMBERHOME/bin/pmemd.cuda
#-------------- Run job -----------------------
$exe  -O -i 0.5_min.in -p glx-co_step1_f.prmtop -o 0.5_min.out -c glx-co_step1_f.inpcrd -r 0.5_min.rst -x 0.5_min.netcdf -inf 0.5_min.mdinfo -ref glx-co_step1_f.inpcrd
echo 'FINISH JOB, SAVE IT TO SCRATCH'
