#!/bin/bash
##SBATCH --mail-user=songlin3@msu.edu
##SBATCH --mail-type=FAIL
#SBATCH -J uMMM_1.0
#SBATCH -e test.err
#SBATCH -o test.out
#SBATCH -N 1 -c 1 --gres=gpu:1
#SBATCH --mem=4G
#SBATCH --time=8:00:00

echo $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

#-------------- Load Modules ------------------
module purge
ulimit -c 0
ml -* GCC/7.3.0-2.30 OpenMPI/3.1.1-CUDA Amber/18-AmberTools-19

exe=$AMBERHOME/bin/pmemd.cuda                  

#-------------- Run job -----------------------
echo 'RUN AMBER JOB'
# running command
$exe -O -i 1.0_us.in -o 1.0_us.out -c 1.0_eq.rst -p glx-co_1264_final_vdw.prmtop -r 1.0_us.rst -x 1.0_us.netcdf -inf 1.0_us.mdinfo -ref 1.0_eq.rst
if grep "Total wall time" 1.0_us.out;then
   echo "done"
else
   sbatch 1.0_us.pbs
fi
