#!/bin/bash
##SBATCH --mail-user=songlin3@msu.edu
##SBATCH --mail-type=FAIL
#SBATCH -J eMMM_0
#SBATCH -e test.err
#SBATCH -o test.out
#SBATCH -N 1 -c 1 --gres=gpu:1
#SBATCH --mem=4G
#SBATCH --time=3:30:00

echo $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

#-------------- Load Modules ------------------
module purge
ulimit -c 0
ml -* GCC/7.3.0-2.30 OpenMPI/3.1.1-CUDA Amber/18-AmberTools-19

exe=$AMBERHOME/bin/pmemd.cuda                  

#-------------- Run job -----------------------
echo 'RUN AMBER JOB'
# running command
$exe -O -i 0_eq.in -o 0_eq.out -c us_center.rst -p glx-co_1264_final.prmtop -r 0_eq.rst -x 0_eq.netcdf -inf 0_eq.mdinfo -ref us_center.rst
if grep "Total wall time" 0_eq.out;then
   echo "done"
   sbatch 0_us.pbs
   cp 0_eq.rst ../0.0025/
   cd ../0.0025/
   sbatch 0.0025_eq.pbs
else
   sbatch 0_eq.pbs
fi
