#!/bin/bash
#SBATCH -J HIP-HID
#SBATCH -e test.err
#SBATCH --nodes=1             ### Node count required for the job
#SBATCH --ntasks-per-node=1   ### Nuber of tasks to be launched per Node     
#SBATCH --gres=gpu:1          ### General REServation of gpu:number of gpus
#SBATCH --mem=8G
#SBATCH --time=120:00:00
  
echo $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

#-------------- Load Modules ------------------
ml -* GCC/7.3.0-2.30 OpenMPI/3.1.1-CUDA Amber/18-AmberTools-19

exe=$AMBERHOME/bin/pmemd.cuda

#-------------- Run job -----------------------
echo 'RUN AMBER JOB'
# running command
$exe -O -i min1.in -o min1.out -c hip-hid.inpcrd -p hip-hid.prmtop -r min1.rst -x min1.netcdf -inf min1.mdinfo -ref hip-hid.inpcrd
$exe -O -i min2.in -o min2.out -c min1.rst -p hip-hid.prmtop -r min2.rst -x min2.netcdf -inf min2.mdinfo -ref min1.rst
$exe -O -i min3.in -o min3.out -c min2.rst -p hip-hid.prmtop -r min3.rst -x min3.netcdf -inf min3.mdinfo -ref min2.rst
$exe -O -i min4.in -o min4.out -c min3.rst -p hip-hid.prmtop -r min4.rst -x min4.netcdf -inf min4.mdinfo -ref min3.rst
$exe -O -i min5.in -o min5.out -c min4.rst -p hip-hid.prmtop -r min5.rst -x min5.netcdf -inf min5.mdinfo -ref min4.rst
$exe -O -i heat.in -o heat.out -c min5.rst -p hip-hid.prmtop -r heat.rst -x heat.netcdf -inf heat.mdinfo -ref min5.rst
$exe -O -i eq_1.in -o eq_1.out -c heat.rst -p hip-hid.prmtop -r eq_1.rst -x eq_1.netcdf -inf eq_1.mdinfo -ref heat.rst
$exe -O -i eq_2.in -o eq_2.out -c eq_1.rst -p hip-hid.prmtop -r eq_2.rst -x eq_2.netcdf -inf eq_2.mdinfo -ref eq_1.rst
$exe -O -i eq_3.in -o eq_3.out -c eq_2.rst -p hip-hid.prmtop -r eq_3.rst -x eq_3.netcdf -inf eq_3.mdinfo -ref eq_2.rst
$exe -O -i eq_4.in -o eq_4.out -c eq_3.rst -p hip-hid.prmtop -r eq_4.rst -x eq_4.netcdf -inf eq_4.mdinfo -ref eq_3.rst
$exe -O -i eq_5.in -o eq_5.out -c eq_4.rst -p hip-hid.prmtop -r eq_5.rst -x eq_5.netcdf -inf eq_5.mdinfo -ref eq_4.rst
$exe -O -i eq_6.in -o eq_6.out -c eq_5.rst -p hip-hid.prmtop -r eq_6.rst -x eq_6.netcdf -inf eq_6.mdinfo -ref eq_5.rst
$exe -O -i us.in -o us.out -c eq_6.rst -p hip-hid.prmtop -r us.rst -x us.netcdf -inf us.mdinfo
