#!/bin/bash
##SBATCH --mail-user=songlin3@msu.edu
##SBATCH --mail-type=FAIL
#SBATCH -J 1e50_XXX
#SBATCH -e test.err
#SBATCH -o test.out
#SBATCH -N 1 -c 1 --gres=gpu:1
#SBATCH --mem=8G
#SBATCH --time=3:00:00

echo $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

#-------------- Load Modules ------------------
module purge
ulimit -c 0
module load GNU/6.4.0-2.28  OpenMPI/2.1.2-CUDA
module load Amber/18

exe=$AMBERHOME/bin/pmemd.cuda
#-------------- Run job -----------------------
$exe  -O -i XXX_equi.in -p glx-co_step1_f.prmtop -o XXX_equi.out -c XXX_heat.rst -r XXX_equi.rst -x XXX_equi.netcdf -inf XXX_equi.mdinfo
if grep "Total wall time" XXX_equi.out;then
   sbatch XXX_prod.pbs
else
   sbatch XXX_equi.pbs
fi
echo 'FINISH JOB, SAVE IT TO SCRATCH'
