#!/bin/bash
##SBATCH --mail-user=songlin3@msu.edu
##SBATCH --mail-type=FAIL
#SBATCH -J s1_MMM
#SBATCH -e test.err
#SBATCH -o test.out
#SBATCH -N 1 -c 1 --gres=gpu:1
#SBATCH --mem=8G
#SBATCH --time=00:30:00

echo $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

#-------------- Load Modules ------------------
module purge
module load GNU/6.4.0-2.28  OpenMPI/2.1.2-CUDA
module load Amber/18

exe=$AMBERHOME/bin/pmemd.cuda
#-------------- Run job -----------------------
$exe  -O -i 0.5_min.in -p glx-ni_step1.prmtop -o 0.5_min.out -c glx-ni_step1.inpcrd -r 0.5_min.rst -x 0.5_min.netcdf -inf 0.5_min.mdinfo -ref glx-ni_step1.inpcrd
if grep "Total wall time" 0.5_min.out;then
   echo "done"
else
   sbatch run.pbs
fi
echo 'FINISH JOB, SAVE IT TO SCRATCH'
