#!/bin/bash
#SBATCH -J Co-imi
#SBATCH -e test.err
#SBATCH -o test.out
#SBATCH --nodes=1             ### Node count required for the job
#SBATCH --ntasks-per-node=1   ### Nuber of tasks to be launched per Node     
#SBATCH --gres=gpu:1          ### General REServation of gpu:number of gpus
#SBATCH --mem=8G
#SBATCH --time=3:30:00
  
echo $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

#-------------- Load Modules ------------------
module load GNU/6.4.0-2.28  OpenMPI/2.1.2-CUDA
module load Amber/18

exe=$AMBERHOME/bin/pmemd.cuda

#-------------- Run job -----------------------
echo 'RUN AMBER JOB'
# running command
$exe -O -i prod.in -o prod.out -c equi.rst -p nicoo1264_0.145.prmtop -r prod.rst -x prod.netcdf -inf prod.mdinfo -ref equi.rst
if grep "Total wall time" prod.out;then
   echo 'all done'
else
   sbatch prod.pbs
fi
echo 'FINISH JOB, SAVE IT TO SCRATCH'
