#!/bin/bash
##SBATCH --mail-user=songlin3@msu.edu
##SBATCH --mail-type=FAIL
#SBATCH -J 1pMMM_XXX
#SBATCH -e test.err
#SBATCH -o test.out
#SBATCH -N 1 -c 1 --gres=gpu:1
#SBATCH --mem=8G
#SBATCH --time=6:00:00

echo $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

#-------------- Load Modules ------------------
module load GNU/6.4.0-2.28  OpenMPI/2.1.2-CUDA
module load Amber/18

exe=$AMBERHOME/bin/pmemd.cuda
#-------------- Run job -----------------------
$exe  -O -i XXX_prod.in -p glx-co_step1_f.prmtop -o XXX_prod.out -c XXX_equi.rst -r XXX_prod.rst -x XXX_prod.netcdf -inf XXX_prod.mdinfo
if grep "Total wall time" XXX_prod.out;then
   echo "all  done"
else
   sbatch XXX_prod.pbs
fi
echo 'FINISH JOB, SAVE IT TO SCRATCH'
